name: Download latest COVID-19 Status vaccination

on:
  workflow_dispatch:
  schedule:
    - cron: 58 * * * *

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run download-status
    - run: |
        git config user.name renansalazar
        git config user.email renansalazar.js@gmail.com
        git add .
        git commit -m "feat: Add report for now"
        git push
